//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SpecAlign.rc
//
#define IDR_MANIFEST                    1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_SpecAlignTYPE               129
#define IDD_DIALOG1                     130
#define ID_FILE_IMPORT                  132
#define ID_IMPORT_FILE                  133
#define ID_IMPORT_FOLDER                134
#define ID_FILE_EXPORT                  135
#define ID_EXPORT_FILE                  136
#define ID_Menu                         137
#define ID_PROCESSING_NORMALIZETIC      138
#define ID_PROCESSING_RELATIVEINTENSITIES 139
#define ID_EDIT_REVERT                  140
#define ID_VIEW_AVERAGESPEC             141
#define ID_GRAPH_ZOOM                   142
#define ID_GRAPH_TRACK                  143
#define ID_GRAPH_RESET                  144
#define ID_GRAPH_CURSOR                 145
#define ID_EDIT_UNDOZOOM                146
#define ID_EDIT_REVERTALLZOOM           148
#define ID_SPECTRUM_VIEWAS              149
#define ID_VIEWAS_LINEGRAPH             150
#define ID_VIEWAS_BARGRAPH              151
#define ID_SPECTRUM_PICKPEAKS           152
#define IDD_DIALOG2                     153
#define ID_SPECTRUM_SHOWPEAKS           156
#define ID_SPECTRUM_REMOVEPEAKS         157
#define ID_PROCESSING_ALIGNPEAKS        158
#define IDD_DIALOG3                     159
#define ID_SPECTRUM_PLOTPEAKS           160
#define IDC_CURSOR1                     162
#define ID_EXPORT_MULTIFILE             163
#define ID_SPECTRUM_CROP                164
#define ID_SPECTRUM_REMOVESPECTRUM      165
#define IDD_DIALOG5                     166
#define IDD_DIALOG6                     167
#define ID_PROCESSINGBINS               168
#define IDD_DIALOG7                     169
#define IDC_CURSOR2                     170
#define IDI_ICON1                       175
#define ID_PROCESSING_SMOOTH            176
#define IDD_DIALOG8                     177
#define ID_SPECTRUM_GENERATEAVERAGESPECTRUM 178
#define ID_Menu179                      179
#define ID_SPECTRUM_MERGEWITHAVERAGESPECTRUM 180
#define ID_IMPORT_AVERAGESPECTRUM       181
#define ID_EXPORT_AVERAGESPECTRUM       182
#define IDD_DIALOG9                     183
#define ID_VIEWAS_STACKEDGRAPH          185
#define ID_PROCESSING_SCALE             186
#define IDD_DIALOG10                    187
#define ID_PROCESSING_SUBTRACTBASELINE  188
#define IDD_DIALOG11                    189
#define ID_SPECTRUM_MANUALPICKPEAKS     190
#define IDC_CURSOR3                     191
#define ID_SPECTRUM_AUTOSCALE           192
#define IDD_DIALOG4                     193
#define ID_SPECTRUM_MANUALREMOVEPEAKS   194
#define IDC_CURSOR4                     195
#define ID_SPECTRUM_CROPFROM            196
#define IDD_DIALOG12                    197
#define ID_VIEWAS_OVERLAPPINGGRAPH      198
#define ID_PROCESSING_RESCALETOPOSITIVE 199
#define ID_PROCESSING_REMOVENEGATIVE    200
#define ID_TOOLS_COMBINESPECTRA         201
#define ID_TOOLS_SUBTRACTSPECTRA        202
#define IDD_DIALOG13                    203
#define IDD_DIALOG14                    204
#define ID_TOOLS_COMPARESPECTRA         205
#define IDD_DIALOG15                    206
#define IDD_DIALOG16                    207
#define ID_TOOLS_COMPAREALL             208
#define ID_PROCESSING_SPECTRAALIGNMENTBYBESTFIT 209
#define IDD_DIALOG17                    210
#define ID_PROCESSING_SPECTRAALIGNMENT  211
#define ID_SPECTRAALIGNMENT_COMBINEDMETHOD 212
#define IDD_DIALOG18                    213
#define IDD_DIALOG19                    214
#define ID_SPECTRAALIGNMENT_CHOICE      215
#define ID_VIEW_FASTDRAW                216
#define ID_TOOLS_GENERATECORRELELOGRAPH 217
#define IDD_DIALOG20                    218
#define ID_SPECTRAALIGNMENT_FFTMETHOD   219
#define IDD_DIALOG21                    220
#define ID_EXPORT_PEAKS                 221
#define IDD_DIALOG22                    223
#define IDD_DIALOG23                    224
#define IDD_DIALOG24                    225
#define IDB_BITMAP1                     227
#define IDD_DIALOG25                    228
#define IDD_DIALOG26                    229
#define IDC_BUTTON1                     1001
#define IDC_EDIT1                       1007
#define IDC_EDIT2                       1008
#define IDC_EDIT3                       1009
#define IDC_NTGRAPHCTRL1                1010
#define IDC_EDIT7                       1010
#define IDC_EDIT8                       1011
#define IDC_EDIT4                       1021
#define IDC_EDIT5                       1022
#define IDC_CHECK1                      1024
#define IDC_CHECK2                      1025
#define IDC_CHECK3                      1026
#define IDC_SLIDER1                     1027
#define IDC_EDIT6                       1028
#define IDC_LIST2                       1035
#define IDC_CHECK4                      1036
#define IDC_CHECK5                      1037
#define IDC_LIST1                       1040
#define IDC_HOTKEY1                     1044
#define IDC_RADIO1                      1045
#define IDC_RADIO2                      1046
#define IDC_RADIO3                      1047
#define IDC_RADIO4                      1048
#define IDC_RADIO5                      1049
#define ID_BUTTON32807                  32807
#define ID_VIEW_BASELINE                32809
#define ID_SPECTRUM_CALCULATEPEAKAREAS  32811
#define ID_EXPORT_PEAKAREA              32813
#define ID_PROCESSING_DENOISE           32814
#define ID_TOOLS_EVALUATEDATASET        32817
#define ID_EXPORT_SPECTRAMODEL          32818

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        230
#define _APS_NEXT_COMMAND_VALUE         32819
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
